#version 450
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D src_yv12;
layout(set = 0, binding = 1, std430) buffer SampleOut {
    vec4 rgba[4];
} out_data;

void main()
{
    out_data.rgba[0] = texture(src_yv12, vec2(0.50, 0.50));
    out_data.rgba[1] = texture(src_yv12, vec2(0.125, 0.125));
    out_data.rgba[2] = texture(src_yv12, vec2(0.875, 0.125));
    out_data.rgba[3] = texture(src_yv12, vec2(0.50, 0.875));
}
